on:
  repository_dispatch:
    types: [test-video]

jobs:
  build:
  
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8]
    steps:
      - uses: browser-actions/setup-chrome@latest
        with:
          chrome-version: stable
      - run: echo $CHROME_VERSION
        env:
          CHROME_VERSION: nihao

      - name: install Chrome_fonts
        run: |
          sudo apt-get install ttf-wqy* -y
      
      - name: config chromedriver
        uses: nanasess/setup-chromedriver@v1

      - name: config chromedriver runrunrun
        run: |
          export DISPLAY=:99
          chromedriver --url-base=/wd/hub &
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          sudo pwd
          sudo python -m pip install requests
          sudo python -m pip install selenium
      - name: get_domain_icp_index_image
        run: |
          curl -O https://raw.githubusercontent.com/aliyungithub1234/test/main/test-video.py
          
      - name: get_domain_icp_index_image run
        run: |
          sudo python test-video.py --video_url ${{ github.event.client_payload.video_url }}
          
